name: Live Batch 3

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 340

    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install gdown
          ffmpeg -version

      - name: Download videos
        run: |
          gdown "https://drive.google.com/uc?id=1DmdhPFhm2Gi5e-CVhuUbq48WI8wEFVbb" -O 01.mp4
          gdown "https://drive.google.com/uc?id=1PeYA3MxFUw1eEQL4pFhzGsYTRAR95bvo" -O 02.mp4

      - name: Check videos
        run: |
          ffprobe -v error -show_entries format=duration \
          -of default=noprint_wrappers=1 01.mp4

          ffprobe -v error -show_entries format=duration \
          -of default=noprint_wrappers=1 02.mp4

      - name: Create playlist
        run: |
          printf "file '01.mp4'\nfile '02.mp4'\n" > playlist.txt
          cat playlist.txt

      - name: Start YouTube + Facebook Live
        env:
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
          FACEBOOK_STREAM_KEY: ${{ secrets.FACEBOOK_STREAM_KEY }}
        run: |
          ffmpeg -hide_banner -loglevel info \
            -re \
            -stream_loop -1 \
            -f concat -safe 0 -i playlist.txt \
            -map 0:v:0 \
            -map 0:a:0 \
            -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,fps=30,format=yuv420p" \
            -c:v libx264 \
            -preset veryfast \
            -profile:v main \
            -level 4.0 \
            -b:v 4500k \
            -maxrate 4500k \
            -bufsize 9000k \
            -r 30 \
            -g 60 \
            -keyint_min 60 \
            -sc_threshold 0 \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -ac 2 \
            -af "aresample=async=1:first_pts=0" \
            -f tee \
            "[f=flv]rtmp://a.rtmp.youtube.com/live2/${YOUTUBE_STREAM_KEY}|[f=flv]rtmps://live-api-s.facebook.com:443/rtmp/${FACEBOOK_STREAM_KEY}"
